name: Build and Test Library
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test library
        run: ./gradlew clean install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
