name: Development (Build & Test)
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-kotlin-insight-client-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-kotlin-insight-client-

      - name: docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Startup Jira and Insight
        run: docker-compose up -d

      - name: Wait for Jira and Insight
        run: ./scripts/waitingForJira.sh

      - name: Build library
        run: ./gradlew clean install --info

      - name: Integration test for ktor
        run: ./gradlew test --info

      - name: Integration test for confluence
        run: |
          NEW_VERSION=$(./gradlew cV | grep "Project version" | cut -d ":" -f2 | xargs | awk '{print $1}') 
          echo "mvn building version: ${{NEW_VERSION}}"
          mvn clean -f kotlin-insight-client-atlas-test/pom.xml -B verify -Pci -Dlibrary.version=${{NEW_VERSION}}