name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker hub login
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: docker login -u $username -p $password
      - name: Startup Jira and Insight
        run: docker-compose up -d
      - name: Wait for Jira and Insight
        run: ./scripts/waitingForJira.sh
      - name: Build and Test library
        run: ./gradlew test --info